### ISSUE TITLE
Ability to open URL on start

### ISSUE THREAD

**Issue by bencroker** [ddev/ddev-browsersync#53]
Thanks for the great DDEV add-on! Is there any way to have Browsersync open a URL when it starts? The goal here is to have Browsersync auto-inject the [script that it requires](https://browsersync.io/docs#requirements) into the `body` element.

I’ve tried setting the [`open` option](https://browsersync.io/docs/options#option-open) to `true`, `external`, and a URL, but it always results in this error:
```
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
```

**Comment by rfay** [comment]
Hey @bencroker ! 

Since the `ddev browsersync` command is a `web` custom command, that means that it is executed inside `ddev-webserver`, and it doesn't even know that your browser (or the host) exists at all.

`browsersync` (https://github.com/ddev/ddev-browsersync/blob/main/commands/web/browsersync) could certainly be written as a host custom command that did a `ddev exec browser-sync` and then did a `launch` on the resulting port. It could even be a different command or something.

In the meantime though, I *think* a `ddev launch :3000` (or whatever port) on current DDEV would do the job. Also `ddev describe` and just click the link shown there for browsersync.

**Comment by bencroker** [comment]
Thanks, @rfay! This does the trick beautifully, so I’ll just add an alias for it.

```shell
ddev browsersync & ddev launch :3000
```

**Comment by tyler36** [comment]
@bencroker 

PRs are welcome if you would like to contribute.

**Comment by bencroker** [comment]
Happy to, but not sure whether this is a broad enough use-case. I’ve added the cheeky alias `bs` which works well for me.

**Comment by tyler36** [comment]
You could always add a note in the docs. :wink

**Comment by bencroker** [comment]
Done!

**Comment by tyler36** [comment]
Thank you. That should make it easier for someone to find, rather than search through closed issues. 😄
